### ISSUE TITLE
Setup failure

### ISSUE THREAD

**Issue by Drolla** [Paebbels/pyVHDLParser#5]
The setup of this nice tool fails, due to the missing file "README.rst" referenced by setup.py in line 42:
   long_description=open("README.rst").read(),
Running the setup gives the following error:
   FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
It would be great to add a small section to readme.md to explain how the tool should be installed and the example executed.

**Comment by qarlosalberto** [comment]
I have the same error.

**Comment by nfrancque** [comment]
Was this ever resolved?  After modifying the setup.py to point at README.md instead of README.rst I still see other failures.  Both setup.py and just running FrontEnd.py fail on what looks like directory structure not matching expected.

**Comment by Paebbels** [comment]
I did some updates to the project.

The package is now available from PyPI as pre-releases (e.g. v0.4.3).

**Comment by nfrancque** [comment]
@Paebbels thanks for getting back to us!  Confirming that can now pull down and run setup.py without failures as well as install from PyPi.  Should be able to close this.

**Comment by Paebbels** [comment]
I also did lot's of updates to the documentation, which is now at RTFD: https://pyvhdlparser.readthedocs.io/en/latest/Installation.html

After writing some basic documentation for `Frontend.py` I'll continue to fix a major bug since introducing expressions. See #6 .

This project is still in version 0.4.x, it's not a stable product. I consider the 2. pass (blocks) to be 75% done.

Then I want to focus on the instance vs. assignment problem.
